# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Griffin Art Projects
email: info@griffinartprojects.ca
description: > # this means to ignore newlines until "baseurl:"
  Griffin Art Projects is an art gallery space located in North Vancouver that showcases contemporary art exhibitions. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://griffinartprojects.ca"     # the base hostname & protocol for your site
                                  # http://code.adriandiaz.ca/ when testing with GitHub
                                  # http://griffinartprojects.ca 
                                  # http://127.0.0.1:4000/ when testing locally
twitter_username: jekyllrb
github_username:  adriandgr
facebook_username: GriffinArtProjects
instagram_username: griffinartprojects
google_analytics: UA-76826733-1
author: Griffin Art Projects

# Build settings
markdown: kramdown

include: ["_pages"]
permalink: /:categories/:title/

collections:
  exhibitions:
    output: true
    permalink: /exhibitions/:path/
  artworks:
    output: true
    permalink: /artworks/:path/
  events:
    output: true
    permalink: /events/:path/